---
title: "Owner Analysis"
format: html
author: Huong Trinh
date: today
toc: false
toc-depth: 2
number-sections: false
theme: cosmo
execute:
  message: false
  warning: false
---

## Explore, Clean, and Wrangle Data

```{r}
# Load the libraries
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

```{r}
# Read in the data
lobster_abundance <- read_csv(here::here("data/Lobster_Abundance_All_Years_20260108.csv"))

# Explore the data
glimpse(lobster_abundance)
summary(lobster_abundance)
unique(lobster_abundance$SITE)
unique(lobster_abundance$SIZE_MM)

# Convert missing values to NA
lobster_abundance <- lobster_abundance %>%
  mutate(SIZE_MM = na_if(SIZE_MM, -99999))

unique(lobster_abundance$SIZE_MM)

# Make the subset that excludes Naples Reef (NAPL)
not_napl <- lobster_abundance %>%
  filter(SITE != "NAPL")

unique(not_napl$SITE)

# Make the AQUE and size >70 subset
aque_70mm <- lobster_abundance %>%
  filter(SITE == "AQUE" & SIZE_MM >= 70)

glimpse(aque_70mm)

# Find the maximum carapace length by site and month
max_lobster <- lobster_abundance %>%
  group_by(SITE, MONTH) %>%
  summarize(MAX_LENGTH = max(SIZE_MM, na.rm = TRUE))

print(max_lobster)
```


## **Data Visualization**

```{r}
# Histogram of lobster size by site
ggplot(data = lobster_abundance, aes(x = SIZE_MM)) +
  geom_histogram() +
  facet_wrap(~SITE)

# Summarize total lobsters by site and year
lobsters_summarize <- lobster_abundance %>%
  group_by(SITE, YEAR) %>%
  summarize (COUNT = n())

# Line plot of total lobsters by year and site
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_point(aes(color = SITE)) +
  geom_line(aes(color = SITE)) 

# Create small/large size summary for 2019-2021
lobster_size_lrg <- lobster_abundance %>%
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>%
    group_by(SITE, SIZE_BIN) %>%
    summarize(COUNT = n()) %>%
    drop_na()

# Dodged bar graph
ggplot(data = lobster_size_lrg, aes(x = SITE, y = COUNT, fill = SIZE_BIN)) +
  geom_col(position = "dodge")

# Styled line plot
lobster_line_plot <- ggplot(data = lobsters_summarize,
                            aes(x = YEAR, y = COUNT, color = SITE)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_x_continuous(breaks = seq(2012, 2025, 1)) +
  labs(
    title = "Total Lobsters Observed by Year",
    x = "Year",
    y = "Number of Lobsters",
    color = "Site"
  ) +
  theme_light()+
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size = 14, face = "bold"),
    axis.title.y = element_text(size = 14, face = "bold"),
    axis.text.x = element_text(size = 12, angle = 45, vjust = 0.5),
    axis.text.y = element_text(size = 12),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 12), 
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

lobster_line_plot

# Save figure
ggsave(
  filename = here::here("figs/total-lobsters-observed-by-year-line-plot.png"),
  plot = lobster_line_plot,
  width = 8,
  height = 5
)
```
